// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.2
// source: Blob.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Blob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Raw               []byte `protobuf:"bytes,1,opt,name=raw" json:"raw,omitempty"`                         // No compression
	RawSize           *int32 `protobuf:"varint,2,opt,name=raw_size,json=rawSize" json:"raw_size,omitempty"` // Only set when compressed, to the uncompressed size
	ZlibData          []byte `protobuf:"bytes,3,opt,name=zlib_data,json=zlibData" json:"zlib_data,omitempty"`
	LzmaData          []byte `protobuf:"bytes,4,opt,name=lzma_data,json=lzmaData" json:"lzma_data,omitempty"`                              // PROPOSED.
	OBSOLETEBzip2Data []byte `protobuf:"bytes,5,opt,name=OBSOLETE_bzip2_data,json=OBSOLETEBzip2Data" json:"OBSOLETE_bzip2_data,omitempty"` // Deprecated.
}

func (x *Blob) Reset() {
	*x = Blob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Blob_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Blob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blob) ProtoMessage() {}

func (x *Blob) ProtoReflect() protoreflect.Message {
	mi := &file_Blob_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blob.ProtoReflect.Descriptor instead.
func (*Blob) Descriptor() ([]byte, []int) {
	return file_Blob_proto_rawDescGZIP(), []int{0}
}

func (x *Blob) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *Blob) GetRawSize() int32 {
	if x != nil && x.RawSize != nil {
		return *x.RawSize
	}
	return 0
}

func (x *Blob) GetZlibData() []byte {
	if x != nil {
		return x.ZlibData
	}
	return nil
}

func (x *Blob) GetLzmaData() []byte {
	if x != nil {
		return x.LzmaData
	}
	return nil
}

func (x *Blob) GetOBSOLETEBzip2Data() []byte {
	if x != nil {
		return x.OBSOLETEBzip2Data
	}
	return nil
}

var File_Blob_proto protoreflect.FileDescriptor

var file_Blob_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x42, 0x6c, 0x6f, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x9d, 0x01, 0x0a, 0x04, 0x42, 0x6c, 0x6f, 0x62, 0x12, 0x10, 0x0a, 0x03,
	0x72, 0x61, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x72, 0x61, 0x77, 0x12, 0x19,
	0x0a, 0x08, 0x72, 0x61, 0x77, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x72, 0x61, 0x77, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x7a, 0x6c, 0x69,
	0x62, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x7a, 0x6c,
	0x69, 0x62, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x7a, 0x6d, 0x61, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x6c, 0x7a, 0x6d, 0x61, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x2e, 0x0a, 0x13, 0x4f, 0x42, 0x53, 0x4f, 0x4c, 0x45, 0x54, 0x45, 0x5f,
	0x62, 0x7a, 0x69, 0x70, 0x32, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x11, 0x4f, 0x42, 0x53, 0x4f, 0x4c, 0x45, 0x54, 0x45, 0x42, 0x7a, 0x69, 0x70, 0x32, 0x44,
	0x61, 0x74, 0x61, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x64, 0x61, 0x6e, 0x69, 0x6c, 0x73, 0x68, 0x69, 0x6b, 0x2f, 0x6f, 0x73, 0x6d, 0x69,
	0x6d, 0x70, 0x2f, 0x70, 0x61, 0x72, 0x73, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x66, 0x2f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f,
}

var (
	file_Blob_proto_rawDescOnce sync.Once
	file_Blob_proto_rawDescData = file_Blob_proto_rawDesc
)

func file_Blob_proto_rawDescGZIP() []byte {
	file_Blob_proto_rawDescOnce.Do(func() {
		file_Blob_proto_rawDescData = protoimpl.X.CompressGZIP(file_Blob_proto_rawDescData)
	})
	return file_Blob_proto_rawDescData
}

var file_Blob_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Blob_proto_goTypes = []interface{}{
	(*Blob)(nil), // 0: proto.Blob
}
var file_Blob_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Blob_proto_init() }
func file_Blob_proto_init() {
	if File_Blob_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Blob_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Blob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Blob_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Blob_proto_goTypes,
		DependencyIndexes: file_Blob_proto_depIdxs,
		MessageInfos:      file_Blob_proto_msgTypes,
	}.Build()
	File_Blob_proto = out.File
	file_Blob_proto_rawDesc = nil
	file_Blob_proto_goTypes = nil
	file_Blob_proto_depIdxs = nil
}
