// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.2
// source: HeaderBBox.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeaderBBox struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Left   *int64 `protobuf:"zigzag64,1,req,name=left" json:"left,omitempty"`
	Right  *int64 `protobuf:"zigzag64,2,req,name=right" json:"right,omitempty"`
	Top    *int64 `protobuf:"zigzag64,3,req,name=top" json:"top,omitempty"`
	Bottom *int64 `protobuf:"zigzag64,4,req,name=bottom" json:"bottom,omitempty"`
}

func (x *HeaderBBox) Reset() {
	*x = HeaderBBox{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HeaderBBox_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeaderBBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderBBox) ProtoMessage() {}

func (x *HeaderBBox) ProtoReflect() protoreflect.Message {
	mi := &file_HeaderBBox_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderBBox.ProtoReflect.Descriptor instead.
func (*HeaderBBox) Descriptor() ([]byte, []int) {
	return file_HeaderBBox_proto_rawDescGZIP(), []int{0}
}

func (x *HeaderBBox) GetLeft() int64 {
	if x != nil && x.Left != nil {
		return *x.Left
	}
	return 0
}

func (x *HeaderBBox) GetRight() int64 {
	if x != nil && x.Right != nil {
		return *x.Right
	}
	return 0
}

func (x *HeaderBBox) GetTop() int64 {
	if x != nil && x.Top != nil {
		return *x.Top
	}
	return 0
}

func (x *HeaderBBox) GetBottom() int64 {
	if x != nil && x.Bottom != nil {
		return *x.Bottom
	}
	return 0
}

var File_HeaderBBox_proto protoreflect.FileDescriptor

var file_HeaderBBox_proto_rawDesc = []byte{
	0x0a, 0x10, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x42, 0x42, 0x6f, 0x78, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x60, 0x0a, 0x0a, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x42, 0x42, 0x6f, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x12, 0x52, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72,
	0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28, 0x12, 0x52, 0x05, 0x72, 0x69, 0x67, 0x68,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x6f, 0x70, 0x18, 0x03, 0x20, 0x02, 0x28, 0x12, 0x52, 0x03,
	0x74, 0x6f, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x6f, 0x74, 0x74, 0x6f, 0x6d, 0x18, 0x04, 0x20,
	0x02, 0x28, 0x12, 0x52, 0x06, 0x62, 0x6f, 0x74, 0x74, 0x6f, 0x6d, 0x42, 0x38, 0x5a, 0x36, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x61, 0x6e, 0x69, 0x6c, 0x73,
	0x68, 0x69, 0x6b, 0x2f, 0x6f, 0x73, 0x6d, 0x69, 0x6d, 0x70, 0x2f, 0x70, 0x61, 0x72, 0x73, 0x65,
	0x72, 0x2f, 0x70, 0x62, 0x66, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2f,
}

var (
	file_HeaderBBox_proto_rawDescOnce sync.Once
	file_HeaderBBox_proto_rawDescData = file_HeaderBBox_proto_rawDesc
)

func file_HeaderBBox_proto_rawDescGZIP() []byte {
	file_HeaderBBox_proto_rawDescOnce.Do(func() {
		file_HeaderBBox_proto_rawDescData = protoimpl.X.CompressGZIP(file_HeaderBBox_proto_rawDescData)
	})
	return file_HeaderBBox_proto_rawDescData
}

var file_HeaderBBox_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_HeaderBBox_proto_goTypes = []interface{}{
	(*HeaderBBox)(nil), // 0: proto.HeaderBBox
}
var file_HeaderBBox_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_HeaderBBox_proto_init() }
func file_HeaderBBox_proto_init() {
	if File_HeaderBBox_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_HeaderBBox_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeaderBBox); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_HeaderBBox_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_HeaderBBox_proto_goTypes,
		DependencyIndexes: file_HeaderBBox_proto_depIdxs,
		MessageInfos:      file_HeaderBBox_proto_msgTypes,
	}.Build()
	File_HeaderBBox_proto = out.File
	file_HeaderBBox_proto_rawDesc = nil
	file_HeaderBBox_proto_goTypes = nil
	file_HeaderBBox_proto_depIdxs = nil
}
