// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.2
// source: PrimitiveBlock.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrimitiveBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stringtable    *StringTable      `protobuf:"bytes,1,req,name=stringtable" json:"stringtable,omitempty"`
	Primitivegroup []*PrimitiveGroup `protobuf:"bytes,2,rep,name=primitivegroup" json:"primitivegroup,omitempty"`
	// Granularity, units of nanodegrees, used to store coordinates in this block
	Granularity *int32 `protobuf:"varint,17,opt,name=granularity,def=100" json:"granularity,omitempty"`
	// Offset value between the output coordinates coordinates and the granularity grid, in units of nanodegrees.
	LatOffset *int64 `protobuf:"varint,19,opt,name=lat_offset,json=latOffset,def=0" json:"lat_offset,omitempty"`
	LonOffset *int64 `protobuf:"varint,20,opt,name=lon_offset,json=lonOffset,def=0" json:"lon_offset,omitempty"`
	// Granularity of dates, normally represented in units of milliseconds since the 1970 epoch.
	DateGranularity *int32 `protobuf:"varint,18,opt,name=date_granularity,json=dateGranularity,def=1000" json:"date_granularity,omitempty"`
}

// Default values for PrimitiveBlock fields.
const (
	Default_PrimitiveBlock_Granularity     = int32(100)
	Default_PrimitiveBlock_LatOffset       = int64(0)
	Default_PrimitiveBlock_LonOffset       = int64(0)
	Default_PrimitiveBlock_DateGranularity = int32(1000)
)

func (x *PrimitiveBlock) Reset() {
	*x = PrimitiveBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PrimitiveBlock_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrimitiveBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimitiveBlock) ProtoMessage() {}

func (x *PrimitiveBlock) ProtoReflect() protoreflect.Message {
	mi := &file_PrimitiveBlock_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimitiveBlock.ProtoReflect.Descriptor instead.
func (*PrimitiveBlock) Descriptor() ([]byte, []int) {
	return file_PrimitiveBlock_proto_rawDescGZIP(), []int{0}
}

func (x *PrimitiveBlock) GetStringtable() *StringTable {
	if x != nil {
		return x.Stringtable
	}
	return nil
}

func (x *PrimitiveBlock) GetPrimitivegroup() []*PrimitiveGroup {
	if x != nil {
		return x.Primitivegroup
	}
	return nil
}

func (x *PrimitiveBlock) GetGranularity() int32 {
	if x != nil && x.Granularity != nil {
		return *x.Granularity
	}
	return Default_PrimitiveBlock_Granularity
}

func (x *PrimitiveBlock) GetLatOffset() int64 {
	if x != nil && x.LatOffset != nil {
		return *x.LatOffset
	}
	return Default_PrimitiveBlock_LatOffset
}

func (x *PrimitiveBlock) GetLonOffset() int64 {
	if x != nil && x.LonOffset != nil {
		return *x.LonOffset
	}
	return Default_PrimitiveBlock_LonOffset
}

func (x *PrimitiveBlock) GetDateGranularity() int32 {
	if x != nil && x.DateGranularity != nil {
		return *x.DateGranularity
	}
	return Default_PrimitiveBlock_DateGranularity
}

var File_PrimitiveBlock_proto protoreflect.FileDescriptor

var file_PrimitiveBlock_proto_rawDesc = []byte{
	0x0a, 0x14, 0x50, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69, 0x76, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x14, 0x50, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69, 0x76, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa1, 0x02, 0x0a, 0x0e, 0x50, 0x72, 0x69, 0x6d, 0x69,
	0x74, 0x69, 0x76, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x34, 0x0a, 0x0b, 0x73, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x52, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12,
	0x3d, 0x0a, 0x0e, 0x70, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69, 0x76, 0x65, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x50, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69, 0x76, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x0e,
	0x70, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69, 0x76, 0x65, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x25,
	0x0a, 0x0b, 0x67, 0x72, 0x61, 0x6e, 0x75, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x18, 0x11, 0x20,
	0x01, 0x28, 0x05, 0x3a, 0x03, 0x31, 0x30, 0x30, 0x52, 0x0b, 0x67, 0x72, 0x61, 0x6e, 0x75, 0x6c,
	0x61, 0x72, 0x69, 0x74, 0x79, 0x12, 0x20, 0x0a, 0x0a, 0x6c, 0x61, 0x74, 0x5f, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x18, 0x13, 0x20, 0x01, 0x28, 0x03, 0x3a, 0x01, 0x30, 0x52, 0x09, 0x6c, 0x61,
	0x74, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x20, 0x0a, 0x0a, 0x6c, 0x6f, 0x6e, 0x5f, 0x6f,
	0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x14, 0x20, 0x01, 0x28, 0x03, 0x3a, 0x01, 0x30, 0x52, 0x09,
	0x6c, 0x6f, 0x6e, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x2f, 0x0a, 0x10, 0x64, 0x61, 0x74,
	0x65, 0x5f, 0x67, 0x72, 0x61, 0x6e, 0x75, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x18, 0x12, 0x20,
	0x01, 0x28, 0x05, 0x3a, 0x04, 0x31, 0x30, 0x30, 0x30, 0x52, 0x0f, 0x64, 0x61, 0x74, 0x65, 0x47,
	0x72, 0x61, 0x6e, 0x75, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x61, 0x6e, 0x69, 0x6c, 0x73, 0x68,
	0x69, 0x6b, 0x2f, 0x6f, 0x73, 0x6d, 0x69, 0x6d, 0x70, 0x2f, 0x70, 0x61, 0x72, 0x73, 0x65, 0x72,
	0x2f, 0x70, 0x62, 0x66, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x2f,
}

var (
	file_PrimitiveBlock_proto_rawDescOnce sync.Once
	file_PrimitiveBlock_proto_rawDescData = file_PrimitiveBlock_proto_rawDesc
)

func file_PrimitiveBlock_proto_rawDescGZIP() []byte {
	file_PrimitiveBlock_proto_rawDescOnce.Do(func() {
		file_PrimitiveBlock_proto_rawDescData = protoimpl.X.CompressGZIP(file_PrimitiveBlock_proto_rawDescData)
	})
	return file_PrimitiveBlock_proto_rawDescData
}

var file_PrimitiveBlock_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PrimitiveBlock_proto_goTypes = []interface{}{
	(*PrimitiveBlock)(nil), // 0: proto.PrimitiveBlock
	(*StringTable)(nil),    // 1: proto.StringTable
	(*PrimitiveGroup)(nil), // 2: proto.PrimitiveGroup
}
var file_PrimitiveBlock_proto_depIdxs = []int32{
	1, // 0: proto.PrimitiveBlock.stringtable:type_name -> proto.StringTable
	2, // 1: proto.PrimitiveBlock.primitivegroup:type_name -> proto.PrimitiveGroup
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_PrimitiveBlock_proto_init() }
func file_PrimitiveBlock_proto_init() {
	if File_PrimitiveBlock_proto != nil {
		return
	}
	file_StringTable_proto_init()
	file_PrimitiveGroup_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_PrimitiveBlock_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrimitiveBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_PrimitiveBlock_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PrimitiveBlock_proto_goTypes,
		DependencyIndexes: file_PrimitiveBlock_proto_depIdxs,
		MessageInfos:      file_PrimitiveBlock_proto_msgTypes,
	}.Build()
	File_PrimitiveBlock_proto = out.File
	file_PrimitiveBlock_proto_rawDesc = nil
	file_PrimitiveBlock_proto_goTypes = nil
	file_PrimitiveBlock_proto_depIdxs = nil
}
